sources = Dir["**/*.rb"]

task default: :run

task :run do
  ruby "controller.rb"
end

task :setup do
  sh "bundle install"
end

directory "doc"
file "doc" => sources do
  sh "yardoc #{sources.join(" ")}"
end
