sources = Dir["**/*.rb"]

task default: :run

task :run do
  ruby "controller.rb"
end

task :setup do
  sh "bundle install"
end

file doc: sources do |t|
  sh "yardoc #{t.prerequisites.join(" ")}"
end
